### ISSUE TITLE
iOS app will not launch (after some time)

### ISSUE THREAD

**Issue by fluffygimp** [mgatelabs/SCN-VR#1]
A day or so after the app has been installed, it will stop opening when attempting to launch.
It'll oftern get to the menu screen for a fraction of a second, before closing out back to icon view.
no matter whether I kill the app, hard reset the iphone, nothing fixes this once it starts.

The only remedy is to remove the app and reinstall.
however this comes at much frustration as I must then copy the videos back onto the device each time.

extra info:
I'm using iExplorer to copy videos onto the device (21GB in total)
I have also made custom thumbnails for the videos, replacing the existing PNG's (alpha'ed in the same way)
Running on iPhone 6 plus with 128GB

**Comment by mgatelabs** [comment]
Did you mess with the setting to auto start in the file manager?  It's broken.

**Comment by fluffygimp** [comment]
very likely actually, I will avoid.
Thank you!

**Comment by mgatelabs** [comment]
Hey, if you would be inclined I have a 1.5 beta currently available.  I fixed that startup issue, it now goes to the content browser instead and it support high resolution still images.  Also the menu is now actual 3D, because of iOS 9 bugs.

**Comment by fluffygimp** [comment]
awesome, sounds good, is the beta through test flight?

**Comment by mgatelabs** [comment]
Yes, you just need me to register you, I normally take requests by private messages on the Facebook group, or you can pm me here, I just need to know an email address tied to iTunes.
