### ISSUE TITLE
Example app crash on startup

### ISSUE THREAD

**Issue by NickAtGit** [mgatelabs/SCN-VR#3]

**Comment by mgatelabs** [comment]
I think the example app is a bit out of date with the current code.  I need to play with the project and see what I need to do since the Mobile VR Station 1.6 changes have been causing a lot of havoc.

**Comment by mgatelabs** [comment]
I figured it out, I needed to add the SCNVRResourceBundle.bundle to the HelloWorld project.  The bundle contains a strings reference thats needed.  I uploaded new source.

**Comment by getarobo** [comment]
Has this pushed to master?

**Comment by mgatelabs** [comment]
Well, there are more fixes required, from testing iPhone 4S, iPhone 5 & iPhone 5C all failed to load from bundles.  A few string files need to be copied into the main app bundle for it to work.  I'll try to post up more changes later today, i've been so busy on Mobile VR Station I haven't committed anything lately.

**Comment by mgatelabs** [comment]
It should all be in.

**Comment by getarobo** [comment]
Thank you so much, I will try it out tell you how it goes!

**Comment by mgatelabs** [comment]
Closing
