### ISSUE TITLE
video texture only shows on left cam.

### ISSUE THREAD

**Issue by getarobo** [mgatelabs/SCN-VR#4]
Hi, 

I been trying to use this as a 360 video VR player, but it only seems to render the sphere on the left side of the cam. This is what I am doing
` 
_player = [[AVPlayer alloc] initWithURL:videoPath];
    _videoSpriteKitNode = [SKVideoNode videoNodeWithFileNamed:@"vr.mp4"];
    _videoNode = [[SCNNode alloc] init];

  [_videoNode setGeometry:[SCNSphere sphereWithRadius:300.f]];

```
_spriteKitScene = [[SKScene alloc] initWithSize:CGSizeMake(2500, 2500)];
[_spriteKitScene setScaleMode:SKSceneScaleModeAspectFit];
[_videoSpriteKitNode setPosition:CGPointMake(_spriteKitScene.size.width/2, _spriteKitScene.size.height/2)];
[_videoSpriteKitNode setSize:_spriteKitScene.size];

[_spriteKitScene addChild:_videoSpriteKitNode];

[_videoNode.geometry.firstMaterial.diffuse setContents:_spriteKitScene];
[_videoNode.geometry.firstMaterial setDoubleSided:true];

[_videoNode setPosition:SCNVector3Make(0, 0, 0)];
[world addChildNode:_videoNode];`
```

Am I missing somthing? or anyhow how to make this work? 
Thanks!

**Comment by mgatelabs** [comment]
Make sure to set the categoryBitMask to 3.  1 for Left side, 2 for right side.

**Comment by getarobo** [comment]
You're the best. Thank you!
