### ISSUE TITLE
arm64 error for Hello World Demo

### ISSUE THREAD

**Issue by ashwingattani** [mgatelabs/SCN-VR#6]
I am getting linking error when i build HelloWorld as

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_AspectDistortionWizardItem", referenced from:
      objc-class-ref in libscn-vr.a(WizardManager.o)
```

scn-vr library build successfully, however on running HelloWorld gives error.

**Comment by mgatelabs** [comment]
The class AspectDistortionWizardItem is definitely inside SCN-VR.  Maybe it's missing from the list of classes to export.  I'll have to check.

**Comment by mgatelabs** [comment]
I updated the code again.  I was able to get hello world to build and deploy

**Comment by ashwingattani** [comment]
working perfectly fine thanks 👍  😄

**Comment by mgatelabs** [comment]
All, good, closing
